### ISSUE TITLE
Question: which Ogre to use for ignition-fortress

### ISSUE THREAD

**Issue by ggulgulia** [gazebo-forks/ogre-2.3-release#2]
Hello there,

* we are creating conan recipes for ignition-gazebo (fortress) for Ubuntu18.04 and Ubuntu22.04 systems and are confused on which ogre to use
***Question** Is it recommended to use the official ogre-next ? 
    - If **yes** : which version of official ogre should be used for ignition-fortress ? 2.1 or 2.2 or 2.3
    - If **No**: what is the difference b/w official ogre and gazebo-forked ogre ? and which version is recommended ?

**Comment by chapulina** [comment]
Hi @ggulgulia , thank you for creating the recipes.

> Is it recommended to use the official ogre-next ? 

It's safer to use it from our forks. We try to upstream as much as we can, but often we need to make changes to the source and / or debian metadata to support side-by-side installation of multiple versions.

>  which version of official ogre should be used for ignition-fortress ? 2.1 or 2.2 or 2.3

Fortress uses Ogre 2.2 from https://github.com/gazebo-forks/ogre-2.2-release
